language: php
sudo: false

php:
  - 8.0
  - 8.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./tests/apc.ini; fi;
  - wget -O phpdoc.phar https://github.com/phpDocumentor/phpDocumentor/releases/download/v3.3.1/phpDocumentor.phar
  - composer install

script:
  - composer test
  - composer cs-check
  - composer docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./docs
  on:
    branch: master
